#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Programa.Resource", IsApplication=true)]

namespace Programa
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06000c
			public const int btInsertar = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int btOrdenar = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int btOrdenarApellido = 2131099662;
			
			// aapt resource value: 0x7f06000f
			public const int btTfn = 2131099663;
			
			// aapt resource value: 0x7f06000b
			public const int cbFamNu = 2131099659;
			
			// aapt resource value: 0x7f060008
			public const int etApellido = 2131099656;
			
			// aapt resource value: 0x7f060006
			public const int etNombre = 2131099654;
			
			// aapt resource value: 0x7f06000a
			public const int etTelefono = 2131099658;
			
			// aapt resource value: 0x7f060012
			public const int iEliminar = 2131099666;
			
			// aapt resource value: 0x7f060011
			public const int iModificar = 2131099665;
			
			// aapt resource value: 0x7f060000
			public const int linearLayout1 = 2131099648;
			
			// aapt resource value: 0x7f060010
			public const int lvDatos = 2131099664;
			
			// aapt resource value: 0x7f060007
			public const int textView2 = 2131099655;
			
			// aapt resource value: 0x7f060009
			public const int textView3 = 2131099657;
			
			// aapt resource value: 0x7f060002
			public const int tvApellido = 2131099650;
			
			// aapt resource value: 0x7f060004
			public const int tvFamilia = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int tvNomb = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int tvNombre = 2131099649;
			
			// aapt resource value: 0x7f060003
			public const int tvTelefono = 2131099651;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int AdaptPerso = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f050000
			public const int menu_context = 2131034112;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
